- name: distribute etcd binaries
  copy: src={{ BASE_DIR }}/bin/etcd-bin/3.3.9/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - etcd
  - etcdctl

- name: create etcd cert dir
  file: name=/etc/etcd/ssl state=directory

- name: distribute etcd-csr.json
  template: src=etcd-csr.json.j2 dest=/etc/etcd/ssl/etcd-csr.json

- name: generate etcd certs
  shell: "cd /etc/etcd/ssl && {{ BIN_DIR }}/cfssl gencert \
        -ca={{ CA_DIR }}/ca.pem \
        -ca-key={{ CA_DIR }}/ca-key.pem \
        -config={{ CA_DIR }}/ca-config.json \
        -profile=kubernetes etcd-csr.json | {{ BIN_DIR }}/cfssljson -bare etcd"

- name: create etcd work dir
  file: name=/var/lib/etcd state=directory

- name: distribute etcd service configuration file
  template: src=etcd.service.j2 dest=/etc/systemd/system/etcd.service

- name: start etcd service
  shell: systemctl daemon-reload && systemctl enable etcd && systemctl restart etcd
