- name: enable common dirs
  file: name={{ item }} state=directory
  with_items:
  - "{{ CA_DIR }}"
  - /root/.kube
  - /etc/docker

- name: distribute cfssl tools
  copy: src={{ BASE_DIR }}/bin/cfssl-bin/1.2.0/{{ item }} dest={{ BIN_DIR }}/{{ item }} mode=0755
  with_items:
  - cfssl
  - cfssl-certinfo
  - cfssljson

- name: distribute CA certs
  copy: src={{ item }} dest={{ CA_DIR }}/{{ item }} mode=0644
  with_items:
  - ca.pem
  - ca-key.pem
  - ca.csr
  - ca-config.json